# HellPot Default Docker Configuration

[logger]
debug = false
trace = false
nocolor = false
use_date_filename = true
directory = "/logs/"
docker_logging = false
log_file_prefix = "hellpot"
console_time_format = "15:04:05"

[http]
bind_addr = "0.0.0.0"
bind_port = "8080"
real_ip_header = "X-Real-IP"
uagent_string_blacklist = ["Cloudflare-Traffic-Manager"]

[http.router]
catchall = false
makerobots = true
paths = ["wp-login.php", "wp-login"]

[performance]
restrict_concurrency = false
max_workers = 256

[deception]
server_name = "nginx"
